### ISSUE TITLE
`supports_inactive_user` attribute required by django 1.3

### ISSUE THREAD

**Issue by divadrei** [maraujop/django-rules#5]
Deprecation warning for django 1.3 :
django/contrib/auth/**init**.py:36: DeprecationWarning: Authentication backends without a `supports_inactive_user` attribute are deprecated. Please define it in class 'django_rules.backends.ObjectPermissionBackend'>
  DeprecationWarning)

**Comment by maraujop** [comment]
Thanks for reporting this @oxys.

I'm not using Django 1.3 yet, because it is not in stable. I didn't know anything of this. I will work on a small fix now.

**Comment by divadrei** [comment]
Thanks, it's just deprecated django rules still works with django 1.3

**Comment by maraujop** [comment]
I just fixed this,

The problem is that they added a new variable to authentication backends in Django 1.3. Not for the moment they throw a `DeprecationWarning` but everything works the same.

Thanks for reporting the issue! :D
